exports.options = {
  NAME: { code: 1, txt: 'Nome' },
  REGISTRATION: { code: 2, txt: 'Matrícula' },
  DOB: { code: 3, txt: 'Data de nascimento' },
  AGE_WHEN_DIAGNOSED: { code: 4, txt: 'Idade do diagnóstico' },
  GENRE: { code: 5, txt: 'Sexo' },
  NEIGHBORHOOD: { code: 6, txt: 'Bairro' },
  CITY: { code: 7, txt: 'Cidade' },
  STATE: { code: 8, txt: 'Estado' },
  SMOKE: { code: 9, txt: 'Fuma?' },
  STOPPED_SMOKING: { code: 10, txt: 'Parou de fumar?' },
  DRINK: { code: 11, txt: 'Bebe?' },
  STOPPED_DRINKING: { code: 12, txt: 'Parou de beber?' },
  EXTERNAL_LESION: { code: 13, txt: 'Lesão extra-bucal' },
  INTERNAL_LESION: { code: 14, txt: 'Lesão intra-bucal' },
  INTERNAL_LESION_LOC: { code: 15, txt: 'Localização da lesão' },
  CLINICAL_DIAGNOSIS: { code: 16, txt: 'Diagnóstico clínico' },
  ADDITIONAL_EXAMS: { code: 17, txt: 'Exames adicionais' },
  FINAL_DIAGNOSIS: { code: 18, txt: 'Diagnóstico final' },
}
